const dataArray:TdataArray = {
    "EN": [
    "terms",
    "terms and conditions",
    "terms & conditions",
    "T&C",
    "legal notice",
    "terms of service",
    "terms of use",
    "ToS",
    "conditions of use",
    "general selling conditions",
    "conditions of use & sale",
    "Ts&Cs",
    "legal notifications"
    ],
    "IT": [
    "termini",
    "termini e condizioni",
    "termini & condizioni",
    "termini di utilizzo",
    "note legali",
    "termini del servizio",
    "condizioni d'uso",
    "condizioni d'utilizzo",
    "condizioni di utilizzo",
    "condizioni generali d'uso",
    "condizioni e termini d'uso",
    "condizioni del servizio",
    "termini di servizio",
    "condizioni generali del servizio",
    "condizioni generali di servizio",
    "condizioni generali",
    "condizioni per l'utilizzo",
    "condizioni",
    "condizioni generali di vendita",
    "condizioni generali di uso e vendita",
    "menzioni legali"
    ],
    "ES": [
    "términos",
    "condiciones generales",
    "condiciones",
    "condiciones del servicio",
    "aviso legal",
    "términos del servicio",
    "condiciones de uso",
    "condiciones de uso y venta",
    "notificaciones legales",
    "términos de uso",
    "condiciones de utilización",
    "términos de servicio",
    "aviso legal",
    "condiciones generales de contratación"
    ],
    "FR": [
    "termes",
    "conditions générales",
    "conditions générales de vente",
    "conditions d'utilisation et generales de vente",
    "mentions légales",
    "conditions d’utilisation",
    "modalités et conditions",
    "conditions générales de vente",
    "conditions de vente",
    "conditions générales d'utilisation",
    "Termes et Conditions d'utilisation",
    "Conditions générales d'utilisation du site",
    "Mentions légales et conditions générales d'utilisation",
    "conditions"
    ],
    "DE": [
    "Geschäftsbedingungen",
    "Allgemeine Geschäftsbedingungen",
    "AGBs",
    "Rechtlicher Hinweis",
    "Nutzungsbedingungen",
    "Benutzungsbedingungen",
    "Allgemeine Verkaufsbedingungen",
    "Kaufs- und Nutzungsbedingungen",
    "Rechtliche Hinweise"
    ],
    "PT-BR": [
    "termos",
    "termos e condições",
    "termos de uso",
    "termos de utilização",
    "nota legal",
    "termos de serviço",
    "condições de uso",
    "termos e condições de Uso",
    "condições de venda",
    "condições"
    ],
    "NL": [
    "voorwaarden",
    "algemene voorwaarden",
    "gebruiks- en verkoopvoorwaarden",
    "servicevoorwaarden",
    "gebruiksvoorwaarden",
    "algemene verkoopvoorwaarden",
    "Algemene condities",
    "Algemene dienstverleningsvoorwaarden",
    "verkoopvoorwaarden",
    "Dienstverleningsvoorwaarden",
    "Algemene Verkoop- en Dienstverleningsvoorwaarden",
    "Dienstvoorwaarden",
    "Dienst voorwaarden",
    "Alg. voorwaarden",
    "Gemeenschappelijke voorwaarden",
    "Algemene Bepalingen",
    "Algemene verkoopbepalingen",
    "Verkoopbepalingen",
    "avw",
    "Juridisch disclaimer",
    "juridische disclaimer",
    "Onze voorwaarden"
    ],
    "RU": [
    "условия",
    "положения и условия",
    "правовое уведомление",
    "юридическая оговорка",
    "условия продажи",
    "условия использования",
    "условия предоставления сервиса",
    "условия предоставления услуг",
    "условия обслуживания",
    "oбщие условия продажи",
    "правовые аспекты"
    ]
}

export type TdataArray = {
    [key:string]:string[]
}

export default dataArray